---
title: "Overtime Dashboard for `r params$LevelTwoName`, as of `r format(Sys.Date() - 3, '%Y/%m/%d')`"
output: 
  flexdashboard::flex_dashboard:
    logo: Z:/Projects/dashboard/RPDCrimeDashboard/Objects/RPDLogoSMALL.png
    orientation: columns
    vertical_layout: fill
    theme: paper
params:
    LevelTwoName:
        label: "CostCenter2ndLevel"
        value: "GRANTS"
    StartDate:
        value: !r as.Date("2017-07-01")
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(tidyverse)
library(scales)
library(DT)
library(lubridate)
library(reshape2)
library(forcats)
library(RColorBrewer)

otpath <- "Z:/Projects/dashboard/RPDOvertimeDashboard/"
fromdate <- params$StartDate
todate <- Sys.Date()

# 2017 pay periods, done manually
days = seq.Date(from = fromdate, to = todate, by = "days") %>%
    as.data.frame()
payperiod2017lookup <- data.frame(
    PayPeriod = c(rep(1, 9), rep(2:100, each = 14))) %>% # Because pay period #1 ended on July 9th 2017
    #"["(., 1:nrow(days),) %>% # filtering by row number - "["() is the function
    mutate(PayPeriod = as.integer(PayPeriod)) %>%
    filter(row_number(.) %in% 1:nrow(days)) %>%
    bind_cols(days) %>%
    # mutate(PayPeriod = as.factor(PayPeriod)) %>%
    rename_(Date = names(.)[2]) # simple rename() doesn't work. renaming 2nd column by index.

payperiod2017range <- payperiod2017lookup %>%
    group_by(PayPeriod) %>%
    summarise(firstdate = min(Date),
              lastdate = max(Date)) %>%
    ungroup()

payperiod2017lookup <- payperiod2017lookup %>%
    left_join(payperiod2017range, by = "PayPeriod")
rm(payperiod2017range, days)

activitylookup <- data.frame(
    ActivityAbrv = LETTERS[c(1:8, 10:24)],
    ActivityFull = c("CityCourt", "CountyCourtOrGJ", "FamilyCourt", "OtherCourt", "MeetingWithDA", "TVB", "TVBSTOPDWI", "PSSAppearance",
                     "CompletingAssignment", "CallBack", "SchoolCrossing", "CommunityMeeting", 
                     "SpecialEvent", "Project", "PersonnelShortage", "AdminMeeting", "TrainingRecd", "TrainingInstorDevelop",
                     "CivilianHoliday", "FTO", "FTOMeeting", "EvidenceTransfer", "Grant"),
    ActivityGrouping = c("Court", "Court", "Court", "Court", "Court", "Court", "Court", "Other", 
                         "CompletingAssignment", "CallBack", "Other", "CommunityMeeting",
                         "Other", "Project", "PersonnelShortage", "Other", "Other", "Other",
                         "Other", "Other", "Other", "Other", "Other"),
    stringsAsFactors = FALSE
)

# Read in data

CostCentersSelected <- read_csv("Z:/Projects/dashboard/RPDOvertimeDashboard/FY1718_Budgets.csv") %>%
    select(CostCenter = `Overtime Allotments`,
           Allotment = `FY18 Budget`,
           LevelTwo = `2nd Level`,
           LevelThree = `3rd Level`,
           LevelFour = `4th Level`) %>%
    filter(LevelTwo == params$LevelTwoName) %>%
    mutate(Allotment = gsub(Allotment, pattern = ",", replacement = "") %>%
               as.numeric(),
           AllottedHours = Allotment / 77) %>%
    select(CostCenter, Allotment, AllottedHours)

otdata <- read_csv(paste0(otpath, "Overtime Table for Dashboards.csv")) %>%
    rename(CostCenter = `Cost Center`,
           PayPeriodListed = Period,
           OvertimeHours = `Overtime Hours`) %>%
    mutate(OvertimeAmount = substr(`Overtime Amount`, start = 2, stop = 99) %>%
               gsub(pattern = ",", replacement = "") %>%
               as.numeric(),
           OvertimeRate = OvertimeAmount / OvertimeHours,
           OTDate = as.Date(`Overtime Calendar Date`, format = "%b %d, %Y"),
           ProjectCodeFactor = `Project Code Description`, #as.factor(`Project Code Description`),
           # CostCenter = as.factor(`Cost Center`),
           CostCenter = case_when(.$CostCenter == "NSC1" ~ "SECT1",
                                  .$CostCenter == "NSC3" ~ "SECT3",
                                  .$CostCenter == "NSC5" ~ "SECT5",
                                  .$CostCenter == "NSC7" ~ "SECT7",
                                  .$CostCenter == "NSC9" ~ "SECT9",
                                  TRUE ~ .$CostCenter),
           WorkingPlatoon = case_when(.$WorkingPlatoon == 1 ~ "FirstPlatoon",
                                      .$WorkingPlatoon == 2 ~ "SecondPlatoon", 
                                      .$WorkingPlatoon == 3 ~ "ThirdPlatoon"),
           WorkingPlatoon = factor(WorkingPlatoon, 
                                   levels = c("FirstPlatoon", "SecondPlatoon", "ThirdPlatoon"))) %>%
    filter(CostCenter %in% CostCentersSelected$CostCenter,
           OTDate >= fromdate) %>%
    left_join(activitylookup, by = c("Activity" = "ActivityAbrv")) %>%
    left_join(payperiod2017lookup, by = c("OTDate" = "Date")) %>%
    mutate(ActivityGrouping = factor(ActivityGrouping, levels = c("Court", 
                                                                  "CompletingAssignment",
                                                                  "CallBack", 
                                                                  "CommunityMeeting", 
                                                                  "Project", 
                                                                  "PersonnelShortage", 
                                                                  "Other"))) %>%
    select(PayPeriodListed, PayPeriod, firstdate, lastdate, OTDate, WorkingPlatoon, 
           CostCenter, ProjectCodeFactor, OvertimeAmount, OvertimeHours, OvertimeRate,
           PersonnelName_New, IBM_New, Rank_New, Type, ActivityFull, ActivityGrouping)

numdistinctCC <- otdata %>% # number of distinct costcenters
    select(CostCenter) %>% 
    distinct() %>% 
    nrow()

pal <- if(numdistinctCC > 2) {
    data.frame(color = brewer.pal(n = numdistinctCC,
                                     name = "Paired"),
                  name = otdata %>% 
                      select(CostCenter) %>% 
                      distinct() %>%
                      arrange(CostCenter),
                  stringsAsFactors = FALSE)
} else { #brewer.pal needs at least 3 colors to make a palette
    data.frame(color = brewer.pal(n = 3, "Set1")[1:numdistinctCC],
               name = otdata %>% 
                      select(CostCenter) %>% 
                      distinct() %>%
                      arrange(CostCenter),
               stringsAsFactors = FALSE)
}
    
otdata <- otdata %>%
    left_join(pal, by = "CostCenter")

numofslips <- nrow(otdata)

```

Overview - Dollars
=====================================================================================

Column {data-width=500 .tabset}
-----------------------------------------------------------------------

### Budgeted

```{r}

if(numofslips == 0) {
    meetbudget <- CostCentersSelected %>%
        #select(Allotment) %>%
        #filter(CostCenter == params$LevelTwoName) %>% 
        mutate(AmountSpent = 0,
               CostCenter = fct_relevel(CostCenter),
               Budget = Allotment) %>%
        as.data.frame()
} else {
    meetbudget <- otdata %>%
        group_by(CostCenter) %>%
        summarise(AmountSpent = sum(OvertimeAmount)) %>%
        left_join(CostCentersSelected, by = "CostCenter") %>%
        mutate(CostCenter = as.factor(CostCenter))

    }

meetbudgetTotal <- data.frame(
    LevelTwo = params$LevelTwoName,
    AmountSpent = sum(meetbudget$AmountSpent, na.rm = TRUE),
    Allotment = sum(meetbudget$Allotment, na.rm = TRUE)
    )

p <- plot_ly(
    data = meetbudgetTotal,
    x = ~LevelTwo,
    y = ~Allotment,
    type = "bar",
    name = "AllottedTotal",
    marker = list(color = "blue"),
    showlegend = FALSE) %>%
    add_trace(y = ~AmountSpent, name = "SpentTotal", marker = list(color = "red"), showlegend = FALSE) %>%
    layout(margin = list(l = 75),
           xaxis = list(title = ""),
           yaxis = list(title = "", exponentformat = "none", tickprefix = "$"),
           barmode = "group",
           hovermode = "closest")
  
q <- plot_ly(
    data = meetbudget,
    x = ~CostCenter,
    y = ~Allotment,
    type = "bar",
    name = "Allotted",
    marker = list(color = "blue")) %>%
    add_trace(y = ~AmountSpent, name = "Spent", marker = list(color = "red")) %>%
    layout(xaxis = list(title = ""),
           yaxis = list(title = "", exponentformat = "none", tickprefix = "$"),
           barmode = "group",
           hovermode = "closest")

subplot(p, q, nrows = 2)

```

### Comp vs Money

```{r}

if(numofslips == 0) {
    cat("No overtime spent")
} else {
    type <- otdata %>%
        group_by(Type) %>%
        summarise(Amount = sum(OvertimeAmount)) %>%
        mutate(Type = factor(Type, levels = c("Cash", "Comp"))) %>%
        complete(Type, fill = list(Amount = 0)) %>%
        mutate(color = case_when(.$Type == "Cash" ~ "forestgreen",
                                 .$Type == "Comp" ~ "darkgrey"))
    typebyCostCenter <- otdata %>%
        group_by(Type, CostCenter) %>%
        summarise(Amount = sum(OvertimeAmount)) %>%
        spread(Type, Amount)
    p <- plot_ly(
        data = type,
        x = ~Type,
        y = ~Amount,
        name = "Dollars",
        type = "bar",
        marker = list(color = ~color),
        showlegend = FALSE) %>%
        layout(hovermode = "closest",
               xaxis = list(title = ""),
               yaxis = list(title = "", exponentformat = "none", tickprefix = "$"))
    q <- plot_ly(
        data = typebyCostCenter,
        x = ~CostCenter,
        y = ~Cash,
        type = "bar",
        name = "Cash",
        marker = list(color = "forestgreen")) %>%
        add_trace(y = ~Comp,
                  name = "Comp",
                  marker = list(color = "darkgrey")) %>%
        layout(barmode = "group",
               yaxis = list(title = "", exponentformat = "none", tickprefix = "$"))
    
    subplot(p, q, nrows = 2)
    }

```

### Working Platoon

```{r}

if(numofslips == 0) {
    cat("No OT worked.")
} else {
    
    workplatoonCostCenter <- otdata %>%
        group_by(WorkingPlatoon, CostCenter) %>%
        summarise(Amount = sum(OvertimeAmount),
                  HoursAmount = sum(OvertimeHours)) %>%
        filter(!is.na(WorkingPlatoon)) %>% # Ditching NA values
        complete(WorkingPlatoon, # To get a trace for platoons that haven't been worked - they get 0 hours & $
                 CostCenter, 
                 fill = list(Amount = 0, HoursAmount = 0)) %>%
        distinct()
    
    workplatoon <- workplatoonCostCenter %>%
        group_by(WorkingPlatoon) %>%
        summarize(Amount = sum(Amount),
                  HoursAmount = sum(HoursAmount)) %>%
        complete(WorkingPlatoon, fill = list(Amount = 0, HoursAmount = 0)) %>%
        mutate(color = case_when(.$WorkingPlatoon == "FirstPlatoon" ~ "lightgrey",
                                 .$WorkingPlatoon == "SecondPlatoon" ~ "lightslategrey", 
                                 .$WorkingPlatoon == "ThirdPlatoon" ~ "slategrey"))
    
    workplatoonCostCenter <- workplatoonCostCenter %>% 
        select(-HoursAmount) %>% 
        spread(WorkingPlatoon, Amount, fill = 0)
        
    p <- plot_ly(
        data = workplatoon,
        x = ~WorkingPlatoon,
        y = ~Amount,
        name = "Platoons",
        type = "bar",
        showlegend = FALSE,
        marker = list(color = ~color),
        text = paste0("$", workplatoon$Amount, " spent on ", workplatoon$HoursAmount, " hours.")) %>%
        layout(xaxis = list(title = ""),
               yaxis = list(title = "", 
                            exponentformat = "none",
                            tickprefix = "$"))
    
    q <- plot_ly(
        data = workplatoonCostCenter,
        x = ~CostCenter,
        y = ~FirstPlatoon,
        type = "bar",
        name = "FirstPlatoon",
        marker = list(color = "lightgrey")) %>%
        add_trace(y = ~SecondPlatoon,
                  name = "SecondPlatoon",
                  marker = list(color = "lightslategrey")) %>%
        add_trace(y = ~ThirdPlatoon,
                  name = "ThirdPlatoon",
                  marker = list(color = "slategrey")) %>%
        layout(yaxis = list(title = "", 
                            barmode = "group", 
                            exponentformat = "none",
                            tickprefix = "$"))

    subplot(p, q, nrows = 2)
    }


```

Column {data-width=500 .tabset}
-----------------------------------------------------------------------

### Project Codes

```{r}

if(numofslips == 0) {
    cat("No OT worked.")
    } else if(nrow(otdata %>% 
                   filter(ProjectCodeFactor != "No Project Code Specified")) == 0) {
        cat("No project codes specified")
    } else {
    
    projectcodes <- otdata %>%
        filter(ProjectCodeFactor != "No Project Code Specified") %>%
        group_by(ProjectCodeFactor, CostCenter) %>%
        summarise(Amount = sum(OvertimeAmount)) %>%
        arrange(desc(Amount)) %>%
        top_n(n = 10, wt = Amount) %>%
        ungroup() %>%
        mutate(ProjectCodeFactor = fct_reorder(ProjectCodeFactor, Amount)) %>%
        spread(CostCenter, Amount, fill = 0) %>%
        #mutate(sumCC = rowSums(.[CostCentersSelected$CostCenter], na.rm = TRUE)) %>%
        mutate(sumCC = rowSums(select(., -ProjectCodeFactor), na.rm = TRUE)) %>%
        arrange(desc(sumCC)) %>%
        top_n(n = 10, wt = sumCC) %>%
        mutate(ProjectCodeFactor = fct_reorder(ProjectCodeFactor, sumCC)) %>% # drop unused factor levels
        as.data.frame()
    
    p <- plot_ly(
        data = projectcodes,
        x = projectcodes[, 2],
        y = ~ProjectCodeFactor,
        name = names(projectcodes)[2],
        marker = list(color = otdata$color[match(names(projectcodes[2]), otdata$CostCenter)]),
        type = "bar",
        orientation = "h")
    
    for(i in 3:(ncol(projectcodes) - 1)) {
        p <- add_trace(
            p,
            x = projectcodes[, i],
            y = ~ProjectCodeFactor,
            marker = list(color = otdata$color[match(names(projectcodes[i]), otdata$CostCenter)]),
            name = names(projectcodes)[i])
    }
    
    p <- p %>%
        layout(margin = list(l = 200),
               legend = list(traceorder = "normal"),
               barmode = "stack",
               hovermode = "y",
               xaxis = list(title = "", exponentformat = "none", tickprefix = "$"),
               yaxis = list(title = ""))
    
    p
    }


```

### Activity Types

```{r}

if(numofslips == 0) {
    cat("No OT worked.")
} else {
    activitytypes <- otdata %>%
        group_by(ActivityGrouping, CostCenter) %>%
        summarise(Amount = sum(OvertimeAmount)) %>%
        mutate(Amount = replace(Amount, is.na(Amount), 0)) %>% # replace NA values with 0
        complete(ActivityGrouping, CostCenter, fill = list(Amount = 0)) %>%
        distinct() %>%
        spread(key = CostCenter, value = Amount) %>%
        ungroup() %>% 
        mutate(sumCC = rowSums(select(., one_of(CostCentersSelected$CostCenter)))) %>% # sumCC sums up the columns with names of cost centers
        as.data.frame()

    p <- plot_ly(
        data = activitytypes,
        y = ~ActivityGrouping,
        x = activitytypes[,2],
        type = "bar",
        marker = list(color = otdata$color[match(names(activitytypes[2]), otdata$CostCenter)]),
        name = names(activitytypes)[2],
        orientation = "h")
    
    for (i in 3:(ncol(activitytypes) - 1)) {
        p <- add_trace(
            p,
            x = activitytypes[, i],
            y = ~ActivityGrouping,
            marker = list(color = otdata$color[match(names(activitytypes[i]), otdata$CostCenter)]),
            name = names(activitytypes)[i])
    }
    
    p <- p %>%
        layout(margin = list(l = 200),
               barmode = "stack",
               legend = list(traceorder = "normal"),
               hovermode = "y",
               xaxis = list(title = "", exponentformat = "none", tickprefix = "$"),
               yaxis = list(title = "", exponentformat = "none", autorange = "reversed"))
    
    p
    }
    

```

### Top Earners

```{r}

if(numofslips == 0) {
    cat("No OT worked.")
} else {
    earners <- otdata %>%
        group_by(PersonnelName_New, CostCenter) %>%
        summarise(Amount = sum(OvertimeAmount)) %>%
        arrange(desc(Amount)) %>%
        ungroup() %>%
        group_by(CostCenter) %>%
        top_n(n = 3, wt = Amount) %>% 
        arrange(desc(Amount)) %>%
        ungroup() %>%
        left_join(pal, by = "CostCenter") %>%
        mutate(ShowLegend = case_when(duplicated(.$CostCenter) ~ FALSE,
                                      TRUE ~ TRUE),
               CostCenter = factor(CostCenter, ordered = TRUE)) %>%
        arrange(CostCenter)
    
    p <- plot_ly(
        type = "bar",
        orientation = "h"
    )
    
    for (i in 1:nrow(earners)) {
        p <- p %>% 
            add_trace(
                data = earners[i ,],
                x = ~Amount,
                y = ~PersonnelName_New,
                legendgroup = ~CostCenter,
                name = ~CostCenter,
                marker = list(color = ~color),
                showlegend = ~ShowLegend
            )
    }
    
    p <- p %>%
        layout(yaxis = list(title = "", 
                            autorange = "reversed",
                            categoryorder = "array",
                            categoryarray = earners %>% arrange(desc(Amount)) %>% .$PersonnelName_New),
               xaxis = list(title = "", 
                            tickprefix = "$", 
                            exponentformat = "none"),
               legend = list(traceorder = "normal"),
               margin = list(l = 150),
               barmode = "stack")

    p
    }

```


Column {data-width=500 .tabset}
-----------------------------------------------------------------------

### Time, by Fiscal Year Pay Period

```{r}

if(numofslips == 0) {
    cat("No OT worked.")
} else {
    
    payperiod <- otdata %>%
        group_by(PayPeriod, CostCenter) %>%
        summarise(Amount = sum(OvertimeAmount)) %>%
        complete(PayPeriod, fill = list(Amount = 0)) %>%
        #mutate(Amount = replace(Amount, is.na(Amount), 0)) %>%
        arrange(PayPeriod) %>%
        left_join(payperiod2017lookup %>% # get the firstdate and lastdate in there
                      select(-Date) %>% 
                      distinct(),
                  by = "PayPeriod") %>%
        spread(CostCenter, Amount, fill = 0) %>%
        left_join(otdata %>% group_by(PayPeriod) %>% summarise(TotalAmount = sum(OvertimeAmount)),
                  by = "PayPeriod") # Instead of doing rowSums - don't need to know CostCenter names this way
    
    # Need a way to get the unused payperiods in there
    
    plotpayperiod <- anti_join(payperiod2017lookup, payperiod, by = "PayPeriod") %>%
        select(-Date) %>%
        distinct() %>%
        mutate(TotalAmount = 0) %>%
        bind_rows(payperiod) %>%
        arrange(PayPeriod)
    
    p <- plot_ly(
        data = plotpayperiod,
        x = ~as.factor(PayPeriod),
        y = ~TotalAmount,
        name = "Total",
        type = "scatter",
        mode = "lines",
        visible = TRUE,
        text = paste0("$",
                      plotpayperiod$TotalAmount,
                      " spent from ",
                      plotpayperiod$firstdate,
                      " to ",
                      plotpayperiod$lastdate))
    
    for (i in 5:ncol(plotpayperiod)) {
        p <- add_trace(
            p,
            y = plotpayperiod[, i],
            name = names(plotpayperiod)[i],
            line = list(color = otdata$color[match(names(plotpayperiod[i]), otdata$CostCenter)]),
            visible = "legendonly",
            text = paste0("$",
                          plotpayperiod[, i],
                          " spent from ",
                          plotpayperiod$firstdate,
                          " to ",
                          plotpayperiod$lastdate))
    }
    p <- p %>%
        layout(hovermode = "closest",
               margin = list(l = 75),
               xaxis = list(title = "Pay Period"),
               yaxis = list(title = "", exponentformat = "none", tickprefix = "$"))
    
    p
    }
```

### Time, By Day

```{r}

if(numofslips == 0) {
    cat("No OT worked.")
} else {
        
    byday <- otdata %>%
        group_by(OTDate, CostCenter) %>%
        summarise(Amount = sum(OvertimeAmount)) %>%
        arrange(desc(Amount)) %>%
        left_join(pal, by = "CostCenter")
    bydaytotal <- byday %>% 
        group_by(OTDate) %>% 
        summarise(TotalAmount = sum(Amount))
    
    p <- plot_ly(
        data = bydaytotal,
        x = ~OTDate,
        y = ~TotalAmount,
        type = "scatter",
        text = paste0("$", 
                      byday$Amount, 
                      " spent on ", 
                      byday$OTDate)) %>%
        layout(hovermode = "closest",
               yaxis = list(title = "", 
                            exponentformat = "none"),
               xaxis = list(title = ""))
    
    q <- plot_ly(
        data = byday,
        x = ~OTDate,
        y = ~Amount,
        marker = list(color = ~color),
        type = "scatter",
        mode = "markers",
        text = paste0("$", byday$Amount, " spent on ", byday$OTDate),
        color = ~CostCenter) %>%
        layout(hovermode = "closest",
               yaxis = list(title = "", 
                            exponentformat = "none",
                            tickprefix = "$"),
               xaxis = list(title = ""))
    
    #subplot(p, q, nrows = 2)
    q
    }

```

### Top Days

```{r}

if(numofslips == 0) {
    cat("No OT worked.")
} else {
    
    # Top 10 days overall, for stacked bar chart
    topdates <- otdata %>%
                   group_by(OTDate) %>%
                   summarise(Amount = sum(OvertimeAmount)) %>%
                   top_n(10, wt = Amount) %>%
                   .$OTDate
    topdays2 <- otdata %>%
        filter(OTDate %in% topdates) %>%
        group_by(OTDate, CostCenter) %>%
        summarise(Amount = sum(OvertimeAmount)) %>%
        ungroup() %>%
        spread(CostCenter, Amount, fill = 0) %>%
        mutate(sumCC = rowSums(select(., -OTDate), na.rm = TRUE)) %>%
        arrange(desc(sumCC)) %>%
        mutate(OTDate = factor(OTDate)) %>%
        mutate(OTDate = factor(OTDate, levels = OTDate)) %>%
        as.data.frame()
    
    p <- plot_ly(
        data = topdays2,
        x = topdays2[, 2], # Start at column 2, since column 1 is OTDate
        y = ~OTDate,
        name = names(topdays2)[2],
        marker = list(color = otdata$color[match(names(topdays2[2]), otdata$CostCenter)]),
        type = "bar",
        orientation = "h")
    
    # Add a trace for each Cost Center
    for(i in 3:(ncol(topdays2) - 1)) { # Stop before you reach the TotalSum column
        p <- add_trace(
            p,
            x = topdays2[, i],
            y = topdays2$OTDate,
            marker = list(color = otdata$color[match(names(topdays2[i]), otdata$CostCenter)]),
            name = names(topdays2)[i])
    }
    p <- p %>%
        layout(barmode = "stack",
               margin = list(l = 200),
               yaxis = list(autorange = "reversed", title = ""),
               xaxis = list(exponentformat = "none", tickprefix = "$"))
    
    p
    
    }

```

Overview - Hours
=====================================================================================

Column {data-width=500 .tabset}
-----------------------------------------------------------------------

### Budgeted

```{r}

if(numofslips == 0) {
    meetbudget <- CostCentersSelected %>%
        #select(Allotment) %>%
        #filter(CostCenter == params$LevelTwoName) %>% 
        mutate(AmountWorked = 0,
               CostCenter = fct_relevel(CostCenter),
               Budget = Allotment) %>%
        as.data.frame()
} else {
    meetbudget <- otdata %>%
        group_by(CostCenter) %>%
        summarise(AmountWorked = sum(OvertimeHours)) %>%
        left_join(CostCentersSelected, by = "CostCenter") %>%
        mutate(CostCenter = as.factor(CostCenter))

    }

meetbudgetTotal <- data.frame(
    LevelTwo = params$LevelTwoName,
    AmountWorked = sum(meetbudget$AmountWorked, na.rm = TRUE),
    AllottedHours = sum(meetbudget$AllottedHours, na.rm = TRUE)
    )

p <- plot_ly(
    data = meetbudgetTotal,
    x = ~LevelTwo,
    y = ~AllottedHours,
    type = "bar",
    name = "AllottedHours",
    marker = list(color = "blue"),
    showlegend = FALSE) %>%
    add_trace(y = ~AmountWorked, name = "WorkedTotal", marker = list(color = "red"), showlegend = FALSE) %>%
    layout(xaxis = list(title = ""),
           yaxis = list(title = "Hours", exponentformat = "none"),
           barmode = "group",
           hovermode = "closest")
  
q <- plot_ly(
    data = meetbudget,
    x = ~CostCenter,
    y = ~AllottedHours,
    type = "bar",
    name = "AllottedHours",
    marker = list(color = "blue")) %>%
    add_trace(y = ~AmountWorked, name = "Worked", marker = list(color = "red")) %>%
    layout(xaxis = list(title = ""),
           yaxis = list(title = "Hours", exponentformat = "none"),
           barmode = "group",
           hovermode = "closest")

subplot(p, q, nrows = 2)

```

### Comp vs Money

```{r}

if(numofslips == 0) {
    cat("No overtime spent")
} else {
    type <- otdata %>%
        group_by(Type) %>%
        summarise(HoursWorked = sum(OvertimeHours)) %>%
        mutate(Type = factor(Type, levels = c("Cash", "Comp"))) %>%
        complete(Type, fill = list(HoursWorked = 0)) %>%
        mutate(color = case_when(.$Type == "Cash" ~ "forestgreen",
                                 .$Type == "Comp" ~ "darkgrey"))
    typebyCostCenter <- otdata %>%
        group_by(Type, CostCenter) %>%
        summarise(HoursWorked = sum(OvertimeHours)) %>%
        spread(Type, HoursWorked, fill = 0)
    p <- plot_ly(
        data = type,
        x = ~Type,
        y = ~HoursWorked,
        name = "Hours",
        type = "bar",
        marker = list(color = ~color),
        showlegend = FALSE) %>%
        layout(hovermode = "closest",
               xaxis = list(title = ""),
               yaxis = list(title = "Hours", exponentformat = "none"))
    q <- plot_ly(
        data = typebyCostCenter,
        x = ~CostCenter,
        y = ~Cash,
        type = "bar",
        name = "Cash",
        marker = list(color = "forestgreen")) %>%
        add_trace(y = ~Comp,
                  name = "Comp",
                  marker = list(color = "darkgrey")) %>%
        layout(barmode = "group",
               yaxis = list(title = "Hours"))
    
    subplot(p, q, nrows = 2, titleY = TRUE)
    }

```

### Working Platoon

```{r}

if(numofslips == 0) {
    cat("No OT worked.")
} else {
    
    workplatoonCostCenter <- otdata %>%
        group_by(WorkingPlatoon, CostCenter) %>%
        summarise(Amount = sum(OvertimeAmount),
                  HoursAmount = sum(OvertimeHours)) %>%
        filter(!is.na(WorkingPlatoon)) %>% # Ditching NA values
        complete(WorkingPlatoon, # To get a trace for platoons that haven't been worked - they get 0 hours & $
                 CostCenter, 
                 fill = list(Amount = 0, HoursAmount = 0)) %>%
        distinct()
    
    workplatoon <- workplatoonCostCenter %>%
        group_by(WorkingPlatoon) %>%
        summarize(Amount = sum(Amount),
                  HoursAmount = sum(HoursAmount)) %>%
        complete(WorkingPlatoon, fill = list(Amount = 0, HoursAmount = 0)) %>%
        mutate(color = case_when(.$WorkingPlatoon == "FirstPlatoon" ~ "lightgrey",
                                 .$WorkingPlatoon == "SecondPlatoon" ~ "lightslategrey", 
                                 .$WorkingPlatoon == "ThirdPlatoon" ~ "slategrey"))
    
    workplatoonCostCenter <- workplatoonCostCenter %>% 
        select(-Amount) %>% 
        spread(WorkingPlatoon, HoursAmount, fill = 0)
    
    p <- plot_ly(
        data = workplatoon,
        x = ~WorkingPlatoon,
        y = ~HoursAmount,
        name = "Platoons",
        type = "bar",
        showlegend = FALSE,
        marker = list(color = ~color),
        text = paste0("$", workplatoon$Amount, " spent on ", workplatoon$HoursAmount, " hours.")) %>%
        layout(xaxis = list(title = ""),
               yaxis = list(title = "Hours", 
                            exponentformat = "none"))
    
    q <- plot_ly(
        data = workplatoonCostCenter,
        x = ~CostCenter,
        y = ~FirstPlatoon,
        type = "bar",
        name = "FirstPlatoon",
        marker = list(color = "lightgrey")) %>%
        add_trace(y = ~SecondPlatoon,
                  name = "SecondPlatoon",
                  marker = list(color = "lightslategrey")) %>%
        add_trace(y = ~ThirdPlatoon,
                  name = "ThirdPlatoon",
                  marker = list(color = "slategrey")) %>%
        layout(yaxis = list(title = "Hours", 
                            barmode = "group", 
                            exponentformat = "none"))

    subplot(p, q, nrows = 2, titleY = TRUE)
    }


```

Column {data-width=500 .tabset}
-----------------------------------------------------------------------

### Project Codes

```{r}

if(numofslips == 0) {
    cat("No OT worked.")
    } else if(nrow(otdata %>% 
                   filter(ProjectCodeFactor != "No Project Code Specified")) == 0) {
        cat("No project codes specified")
    } else {
    
    projectcodes <- otdata %>%
        filter(ProjectCodeFactor != "No Project Code Specified") %>%
        group_by(ProjectCodeFactor, CostCenter) %>%
        summarise(HoursWorked = sum(OvertimeHours)) %>%
        arrange(desc(HoursWorked)) %>%
        top_n(n = 10, wt = HoursWorked) %>%
        ungroup() %>%
        mutate(ProjectCodeFactor = fct_reorder(ProjectCodeFactor, HoursWorked)) %>%
        spread(CostCenter, HoursWorked, fill = 0) %>%
        #mutate(sumCC = rowSums(.[CostCentersSelected$CostCenter], na.rm = TRUE)) %>%
        mutate(sumCC = rowSums(select(., -ProjectCodeFactor), na.rm = TRUE)) %>%
        arrange(desc(sumCC)) %>%
        top_n(n = 10, wt = sumCC) %>%
        mutate(ProjectCodeFactor = fct_reorder(ProjectCodeFactor, sumCC)) %>% # drop unused factor levels
        as.data.frame()
    
    p <- plot_ly(
        data = projectcodes,
        x = projectcodes[, 2],
        y = ~ProjectCodeFactor,
        name = names(projectcodes)[2],
        marker = list(color = otdata$color[match(names(projectcodes[2]), otdata$CostCenter)]),
        type = "bar",
        orientation = "h")
    
    for(i in 3:(ncol(projectcodes) - 1)) {
        p <- add_trace(
            p,
            x = projectcodes[, i],
            y = ~ProjectCodeFactor,
            marker = list(color = otdata$color[match(names(projectcodes[i]), otdata$CostCenter)]),
            name = names(projectcodes)[i])
    }
    
    p <- p %>%
        layout(margin = list(l = 200),
               barmode = "stack",
               hovermode = "y",
               xaxis = list(title = "Hours", exponentformat = "none"),
               yaxis = list(title = ""))
    
    p
    }


```

### Activity Types

```{r}

if(numofslips == 0) {
    cat("No OT worked.")
} else {
    activitytypes <- otdata %>%
        group_by(ActivityGrouping, CostCenter) %>%
        summarise(HoursWorked = sum(OvertimeHours)) %>%
        mutate(HoursWorked = replace(HoursWorked, is.na(HoursWorked), 0)) %>% # replace NA values with 0
        complete(ActivityGrouping, CostCenter, fill = list(HoursWorked = 0)) %>%
        distinct() %>%
        spread(key = CostCenter, value = HoursWorked) %>%
        ungroup() %>% 
        mutate(sumCC = rowSums(select(., one_of(CostCentersSelected$CostCenter)))) %>% # sumCC sums up the columns with names of cost centers
        as.data.frame()

    p <- plot_ly(
        data = activitytypes,
        y = ~ActivityGrouping,
        x = activitytypes[,2],
        type = "bar",
        marker = list(color = otdata$color[match(names(activitytypes[2]), otdata$CostCenter)]),
        name = names(activitytypes)[2],
        orientation = "h")
    
    for (i in 3:(ncol(activitytypes) - 1)) {
        p <- add_trace(
            p,
            x = activitytypes[, i],
            y = ~ActivityGrouping,
            marker = list(color = otdata$color[match(names(activitytypes[i]), otdata$CostCenter)]),
            name = names(activitytypes)[i])
    }
    
    p <- p %>%
        layout(margin = list(l = 200),
               barmode = "stack",
               hovermode = "y",
               xaxis = list(title = "Hours", exponentformat = "none"),
               yaxis = list(title = "", exponentformat = "none", autorange = "reversed"))
    
    p
    }
    

```

### Top Earners

```{r}

if(numofslips == 0) {
    cat("No OT worked.")
} else {
    earners <- otdata %>%
        group_by(PersonnelName_New, CostCenter) %>%
        summarise(HoursWorked = sum(OvertimeHours)) %>%
        arrange(desc(HoursWorked)) %>%
        ungroup() %>%
        group_by(CostCenter) %>%
        top_n(n = 3, wt = HoursWorked) %>% 
        arrange(desc(HoursWorked)) %>%
        ungroup() %>%
        left_join(pal, by = "CostCenter") %>%
        mutate(ShowLegend = case_when(duplicated(.$CostCenter) ~ FALSE,
                                      TRUE ~ TRUE),
               CostCenter = factor(CostCenter, ordered = TRUE)) %>%
        arrange(CostCenter)
    
    p <- plot_ly(
        type = "bar",
        orientation = "h"
    )
    
    for (i in 1:nrow(earners)) {
        p <- p %>% 
            add_trace(
                data = earners[i ,],
                x = ~HoursWorked,
                y = ~PersonnelName_New,
                legendgroup = ~CostCenter,
                name = ~CostCenter,
                marker = list(color = ~color),
                showlegend = ~ShowLegend
            )
    }

    p <- p %>%
        layout(yaxis = list(autorange = "reversed",
                            title = "",
                            categoryorder = "array",
                            categoryarray = earners %>% arrange(desc(HoursWorked)) %>% .$PersonnelName_New),
               xaxis = list(title = ""),
               legend = list(traceorder = "normal"),
               margin = list(l = 150),
               barmode = "stack")
    p
    }

```


Column {data-width=500 .tabset}
-----------------------------------------------------------------------

### Time, by Fiscal Year Pay Period

```{r}

if(numofslips == 0) {
    cat("No OT worked.")
} else {
    
    payperiod <- otdata %>%
        group_by(PayPeriod, CostCenter) %>%
        summarise(HoursWorked = sum(OvertimeHours)) %>%
        complete(PayPeriod, fill = list(HoursWorked = 0)) %>%
        arrange(PayPeriod) %>%
        left_join(payperiod2017lookup %>% # get the firstdate and lastdate in there
                      select(-Date) %>% 
                      distinct(),
                  by = "PayPeriod") %>%
        spread(CostCenter, HoursWorked, fill = 0) %>%
        left_join(otdata %>% group_by(PayPeriod) %>% summarise(HoursWorked = sum(OvertimeHours)),
                  by = "PayPeriod") # Instead of doing rowSums - don't need to know CostCenter names this way
    
    # Need a way to get the unused payperiods in there
    
    plotpayperiod <- anti_join(payperiod2017lookup, payperiod, by = "PayPeriod") %>%
        select(-Date) %>%
        distinct() %>%
        #mutate(TotalAmount = 0) %>%
        bind_rows(payperiod) %>%
        arrange(PayPeriod)
    
    p <- plot_ly(
        data = plotpayperiod,
        x = ~as.factor(PayPeriod),
        y = ~HoursWorked,
        name = "Total",
        type = "scatter",
        mode = "lines",
        visible = TRUE,
        hoverinfo = "text",
        text = paste0(plotpayperiod$HoursWorked,
                      " hours worked from ",
                      plotpayperiod$firstdate,
                      " to ",
                      plotpayperiod$lastdate))
    
    for (i in 4:(ncol(plotpayperiod) - 1) ) {
        p <- add_trace(
            p,
            y = plotpayperiod[, i],
            name = names(plotpayperiod)[i],
            line = list(color = otdata$color[match(names(plotpayperiod[i]), otdata$CostCenter)]),
            visible = "legendonly",
            hoverinfo = "text",
            text = paste0(plotpayperiod[, i],
                          " hours worked from ",
                          plotpayperiod$firstdate,
                          " to ",
                          plotpayperiod$lastdate))
    }
    p <- p %>%
        layout(hovermode = "closest",
               xaxis = list(title = "Pay Period"),
               yaxis = list(title = "Hours", exponentformat = "none"))
    
    p
    }
```

### Time, By Day

```{r}

if(numofslips == 0) {
    cat("No OT worked.")
} else {
        
    byday <- otdata %>%
        group_by(OTDate, CostCenter) %>%
        summarise(HoursWorked = sum(OvertimeHours)) %>%
        arrange(desc(HoursWorked)) %>%
        left_join(pal, by = "CostCenter")
    bydaytotal <- byday %>% 
        group_by(OTDate) %>% 
        summarise(TotalHours = sum(HoursWorked))
    
    p <- plot_ly(
        data = bydaytotal,
        x = ~OTDate,
        y = ~TotalHours,
        type = "scatter",
        mode = "markers",
        hoverinfo = "text",
        text = paste0(bydaytotal$TotalHours, 
                      " hours worked on ", 
                      bydaytotal$OTDate)) %>%
        layout(hovermode = "closest",
               yaxis = list(title = "", 
                            exponentformat = "none"),
               xaxis = list(title = ""))
    
    q <- plot_ly(
        data = byday,
        x = ~OTDate,
        y = ~HoursWorked,
        marker = list(color = ~color),
        type = "scatter",
        mode = "markers",
        hoverinfo = "text",
        text = paste0(byday$HoursWorked, 
                      " hours worked on ", 
                      byday$OTDate, 
                      " by ",
                      byday$CostCenter),
        marker = list(color = ~color)
        ) %>%
        layout(hovermode = "closest",
               yaxis = list(title = "Hours", 
                            exponentformat = "none"),
               xaxis = list(title = ""))
    
    #subplot(p, q, nrows = 2)
    q
    }

```

### Top Days

```{r}

if(numofslips == 0) {
    cat("No OT worked.")
} else {
    
    # Top 10 days overall, for stacked bar chart
    topdates <- otdata %>%
                   group_by(OTDate) %>%
                   summarise(HoursWorked = sum(OvertimeHours)) %>%
                   top_n(10, wt = HoursWorked) %>%
                   .$OTDate
    topdays2 <- otdata %>%
        filter(OTDate %in% topdates) %>%
        group_by(OTDate, CostCenter) %>%
        summarise(HoursWorked = sum(OvertimeHours)) %>%
        ungroup() %>%
        spread(CostCenter, HoursWorked, fill = 0) %>%
        mutate(sumCC = rowSums(select(., -OTDate), na.rm = TRUE)) %>%
        arrange(desc(sumCC)) %>%
        mutate(OTDate = factor(OTDate)) %>%
        mutate(OTDate = factor(OTDate, levels = OTDate)) %>%
        as.data.frame()
    
    p <- plot_ly(
        data = topdays2,
        x = topdays2[, 2], # Start at column 2, since column 1 is OTDate
        y = ~OTDate,
        name = names(topdays2)[2],
        marker = list(color = otdata$color[match(names(topdays2[2]), otdata$CostCenter)]),
        type = "bar",
        orientation = "h")
    
    # Add a trace for each Cost Center
    for(i in 3:(ncol(topdays2) - 1)) { # Stop before you reach the TotalSum column
        p <- add_trace(
            p,
            x = topdays2[, i],
            y = topdays2$OTDate,
            marker = list(color = otdata$color[match(names(topdays2[i]), otdata$CostCenter)]),
            name = names(topdays2)[i])
    }
    p <- p %>%
        layout(barmode = "stack",
               margin = list(l = 200),
               yaxis = list(autorange = "reversed", title = ""),
               xaxis = list(exponentformat = "none", title = "Hours"))
    
    p
    
    }

```

Data
=====================================================================================

### View of data

```{r}

otdata$OTDate <- as.character(otdata$OTDate) # to dump the scroll bar in the datatable

datatable(otdata %>% 
              select(PersonnelName_New, Rank_New, Type, OvertimeHours, OvertimeAmount, OTDate, CostCenter, ProjectCodeFactor, ActivityFull),
          filter = "top", 
          rownames = FALSE,
          colnames = c("Name", "Rank", "Type", "Hours", "Amount", "Date", "Cost Center", "Project Code", "Activity Type"),
          extensions = c("Buttons", "ColReorder"),
          options = list(dom = "Blftp",
                         colReorder = TRUE,
                         pageLength = 20,
                         lengthMenu = c(10, 20, 50, 100),
                         bPaginate = TRUE,
                         columnDefs = list(list(className = "dt-right", 
                                                targets = "_all")
                                           ),
                         buttons = c("csv")
                         )
          )


```